/*
 *  Do not modify this file; it is automatically 
 *  generated and any modifications will be overwritten.
 *
 * @(#) xdc-y23
 */

#ifndef ti_uia_runtime_LoggerStopMode__INTERNAL__
#define ti_uia_runtime_LoggerStopMode__INTERNAL__

#ifndef ti_uia_runtime_LoggerStopMode__internalaccess
#define ti_uia_runtime_LoggerStopMode__internalaccess
#endif

#include <ti/uia/runtime/LoggerStopMode.h>

#undef xdc_FILE__
#ifndef xdc_FILE
#define xdc_FILE__ NULL
#else
#define xdc_FILE__ xdc_FILE
#endif

/* getTransferType */
#undef ti_uia_runtime_LoggerStopMode_getTransferType
#define ti_uia_runtime_LoggerStopMode_getTransferType ti_uia_runtime_LoggerStopMode_getTransferType__F

/* getContents */
#undef ti_uia_runtime_LoggerStopMode_getContents
#define ti_uia_runtime_LoggerStopMode_getContents ti_uia_runtime_LoggerStopMode_getContents__E

/* isEmpty */
#undef ti_uia_runtime_LoggerStopMode_isEmpty
#define ti_uia_runtime_LoggerStopMode_isEmpty ti_uia_runtime_LoggerStopMode_isEmpty__E

/* getMaxLength */
#undef ti_uia_runtime_LoggerStopMode_getMaxLength
#define ti_uia_runtime_LoggerStopMode_getMaxLength ti_uia_runtime_LoggerStopMode_getMaxLength__E

/* getInstanceId */
#undef ti_uia_runtime_LoggerStopMode_getInstanceId
#define ti_uia_runtime_LoggerStopMode_getInstanceId ti_uia_runtime_LoggerStopMode_getInstanceId__E

/* getPriority */
#undef ti_uia_runtime_LoggerStopMode_getPriority
#define ti_uia_runtime_LoggerStopMode_getPriority ti_uia_runtime_LoggerStopMode_getPriority__E

/* setPriority */
#undef ti_uia_runtime_LoggerStopMode_setPriority
#define ti_uia_runtime_LoggerStopMode_setPriority ti_uia_runtime_LoggerStopMode_setPriority__E

/* reset */
#undef ti_uia_runtime_LoggerStopMode_reset
#define ti_uia_runtime_LoggerStopMode_reset ti_uia_runtime_LoggerStopMode_reset__F

/* writeMemoryRange */
#undef ti_uia_runtime_LoggerStopMode_writeMemoryRange
#define ti_uia_runtime_LoggerStopMode_writeMemoryRange ti_uia_runtime_LoggerStopMode_writeMemoryRange__E

/* setModuleIdToRouteToStatusLogger */
#undef ti_uia_runtime_LoggerStopMode_setModuleIdToRouteToStatusLogger
#define ti_uia_runtime_LoggerStopMode_setModuleIdToRouteToStatusLogger ti_uia_runtime_LoggerStopMode_setModuleIdToRouteToStatusLogger__E

/* flushAll */
#undef ti_uia_runtime_LoggerStopMode_flushAll
#define ti_uia_runtime_LoggerStopMode_flushAll ti_uia_runtime_LoggerStopMode_flushAll__F

/* flushAllInternal */
#undef ti_uia_runtime_LoggerStopMode_flushAllInternal
#define ti_uia_runtime_LoggerStopMode_flushAllInternal ti_uia_runtime_LoggerStopMode_flushAllInternal__E

/* flush */
#undef ti_uia_runtime_LoggerStopMode_flush
#define ti_uia_runtime_LoggerStopMode_flush ti_uia_runtime_LoggerStopMode_flush__E

/* getNumDropped */
#undef ti_uia_runtime_LoggerStopMode_getNumDropped
#define ti_uia_runtime_LoggerStopMode_getNumDropped ti_uia_runtime_LoggerStopMode_getNumDropped__E

/* enable */
#undef ti_uia_runtime_LoggerStopMode_enable
#define ti_uia_runtime_LoggerStopMode_enable ti_uia_runtime_LoggerStopMode_enable__E

/* disable */
#undef ti_uia_runtime_LoggerStopMode_disable
#define ti_uia_runtime_LoggerStopMode_disable ti_uia_runtime_LoggerStopMode_disable__E

/* write0 */
#undef ti_uia_runtime_LoggerStopMode_write0
#define ti_uia_runtime_LoggerStopMode_write0 ti_uia_runtime_LoggerStopMode_write0__E

/* write1 */
#undef ti_uia_runtime_LoggerStopMode_write1
#define ti_uia_runtime_LoggerStopMode_write1 ti_uia_runtime_LoggerStopMode_write1__E

/* write2 */
#undef ti_uia_runtime_LoggerStopMode_write2
#define ti_uia_runtime_LoggerStopMode_write2 ti_uia_runtime_LoggerStopMode_write2__E

/* write4 */
#undef ti_uia_runtime_LoggerStopMode_write4
#define ti_uia_runtime_LoggerStopMode_write4 ti_uia_runtime_LoggerStopMode_write4__E

/* write8 */
#undef ti_uia_runtime_LoggerStopMode_write8
#define ti_uia_runtime_LoggerStopMode_write8 ti_uia_runtime_LoggerStopMode_write8__E

/* setFilterLevel */
#undef ti_uia_runtime_LoggerStopMode_setFilterLevel
#define ti_uia_runtime_LoggerStopMode_setFilterLevel ti_uia_runtime_LoggerStopMode_setFilterLevel__E

/* getFilterLevel */
#undef ti_uia_runtime_LoggerStopMode_getFilterLevel
#define ti_uia_runtime_LoggerStopMode_getFilterLevel ti_uia_runtime_LoggerStopMode_getFilterLevel__E

/* getFreeSize */
#undef ti_uia_runtime_LoggerStopMode_getFreeSize
#define ti_uia_runtime_LoggerStopMode_getFreeSize ti_uia_runtime_LoggerStopMode_getFreeSize__E

/* getUnreadSize */
#undef ti_uia_runtime_LoggerStopMode_getUnreadSize
#define ti_uia_runtime_LoggerStopMode_getUnreadSize ti_uia_runtime_LoggerStopMode_getUnreadSize__E

/* readBlockOfMemory */
#define LoggerStopMode_readBlockOfMemory ti_uia_runtime_LoggerStopMode_readBlockOfMemory__I

/* writeBlockOfMemory */
#define LoggerStopMode_writeBlockOfMemory ti_uia_runtime_LoggerStopMode_writeBlockOfMemory__I

/* filterOutEvent */
#define LoggerStopMode_filterOutEvent ti_uia_runtime_LoggerStopMode_filterOutEvent__I

/* postIncrementPtr */
#define LoggerStopMode_postIncrementPtr ti_uia_runtime_LoggerStopMode_postIncrementPtr__I

/* Module_startup */
#undef ti_uia_runtime_LoggerStopMode_Module_startup
#define ti_uia_runtime_LoggerStopMode_Module_startup ti_uia_runtime_LoggerStopMode_Module_startup__F

/* Instance_init */
#undef ti_uia_runtime_LoggerStopMode_Instance_init
#define ti_uia_runtime_LoggerStopMode_Instance_init ti_uia_runtime_LoggerStopMode_Instance_init__F

/* Instance_finalize */
#undef ti_uia_runtime_LoggerStopMode_Instance_finalize
#define ti_uia_runtime_LoggerStopMode_Instance_finalize ti_uia_runtime_LoggerStopMode_Instance_finalize__F

/* module */
#define LoggerStopMode_module ((ti_uia_runtime_LoggerStopMode_Module_State *)(xdc__MODOBJADDR__(ti_uia_runtime_LoggerStopMode_Module__state__V)))
#if !defined(__cplusplus) || !defined(ti_uia_runtime_LoggerStopMode__cplusplus)
#define module ((ti_uia_runtime_LoggerStopMode_Module_State *)(xdc__MODOBJADDR__(ti_uia_runtime_LoggerStopMode_Module__state__V)))
#endif
/* per-module runtime symbols */
#undef Module__MID
#define Module__MID ti_uia_runtime_LoggerStopMode_Module__id__C
#undef Module__DGSINCL
#define Module__DGSINCL ti_uia_runtime_LoggerStopMode_Module__diagsIncluded__C
#undef Module__DGSENAB
#define Module__DGSENAB ti_uia_runtime_LoggerStopMode_Module__diagsEnabled__C
#undef Module__DGSMASK
#define Module__DGSMASK ti_uia_runtime_LoggerStopMode_Module__diagsMask__C
#undef Module__LOGDEF
#define Module__LOGDEF ti_uia_runtime_LoggerStopMode_Module__loggerDefined__C
#undef Module__LOGOBJ
#define Module__LOGOBJ ti_uia_runtime_LoggerStopMode_Module__loggerObj__C
#undef Module__LOGFXN0
#define Module__LOGFXN0 ti_uia_runtime_LoggerStopMode_Module__loggerFxn0__C
#undef Module__LOGFXN1
#define Module__LOGFXN1 ti_uia_runtime_LoggerStopMode_Module__loggerFxn1__C
#undef Module__LOGFXN2
#define Module__LOGFXN2 ti_uia_runtime_LoggerStopMode_Module__loggerFxn2__C
#undef Module__LOGFXN4
#define Module__LOGFXN4 ti_uia_runtime_LoggerStopMode_Module__loggerFxn4__C
#undef Module__LOGFXN8
#define Module__LOGFXN8 ti_uia_runtime_LoggerStopMode_Module__loggerFxn8__C
#undef Module__G_OBJ
#define Module__G_OBJ ti_uia_runtime_LoggerStopMode_Module__gateObj__C
#undef Module__G_PRMS
#define Module__G_PRMS ti_uia_runtime_LoggerStopMode_Module__gatePrms__C
#undef Module__GP_create
#define Module__GP_create ti_uia_runtime_LoggerStopMode_Module_GateProxy_create
#undef Module__GP_delete
#define Module__GP_delete ti_uia_runtime_LoggerStopMode_Module_GateProxy_delete
#undef Module__GP_enter
#define Module__GP_enter ti_uia_runtime_LoggerStopMode_Module_GateProxy_enter
#undef Module__GP_leave
#define Module__GP_leave ti_uia_runtime_LoggerStopMode_Module_GateProxy_leave
#undef Module__GP_query
#define Module__GP_query ti_uia_runtime_LoggerStopMode_Module_GateProxy_query

/* Object__sizingError */
#line 1 "Error_inconsistent_object_size_in_ti.uia.runtime.LoggerStopMode"
typedef char ti_uia_runtime_LoggerStopMode_Object__sizingError[sizeof(ti_uia_runtime_LoggerStopMode_Object) > sizeof(ti_uia_runtime_LoggerStopMode_Struct) ? -1 : 1];


#endif /* ti_uia_runtime_LoggerStopMode__INTERNAL____ */
